management:
  endpoints:
    web:
      exposure:
        include: health, info  # Expose the health and info endpoints
  health:
    discovery:
      enabled: true
  eureka:
    instance:
      leaseRenewalIntervalInSeconds: 30  # Default is 30 seconds
      leaseExpirationDurationInSeconds: 90 # Default is 90 seconds